import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Chatbot, Footer, Header } from "../site-shell";

export const metadata: Metadata = {title:"About Maria Semeco",description:"Meet Maria Semeco, founder of Semeco Digital, and learn how she uses modern technology and AI to help small businesses.",alternates:{canonical:"/about"},openGraph:{title:"About Maria Semeco | Semeco Digital",description:"Founder-led digital support for local businesses.",url:"/about"}};

export default function About(){return <main><Header/>
  <section className="inner-hero about-hero"><div className="shell inner-grid"><div><p className="eyebrow light"><span/> Founder of Semeco Digital</p><h1>Modern technology should make business <em>easier—not more complicated.</em></h1><p>I’m Maria Semeco. I help small businesses use websites, marketing, content, and AI in practical ways that support real people and everyday work.</p><Link className="button cream" href="/contact">Book a Free Consultation <span>↗</span></Link></div><div className="portrait-large founder-photo"><Image src="/maria-semeco-founder.jpg" alt="Maria Semeco, founder of Semeco Digital" fill sizes="(max-width: 900px) 100vw, 40vw" priority/></div></div></section>
  <section className="section shell"><div className="bio-grid"><div><p className="eyebrow"><span/> My story</p><h2>Professional digital tools should be <em>within reach.</em></h2></div><div><p>I founded Semeco Digital because I believe small businesses should have access to professional digital tools without paying the cost of a large agency.</p><p>I’m passionate about entrepreneurship, modern technology, AI, digital marketing, and helping small businesses grow. I have completed several projects using AI for website creation, branding, copywriting, automation, content planning, and business systems. Those projects showed me how useful technology can be when it is paired with clear goals and thoughtful human judgment.</p><p>My goal is to use AI to make people’s work easier, reduce repetitive tasks, improve customer experiences, and help businesses become more successful. That does not mean adding technology everywhere. It means choosing tools carefully and building systems that solve a real problem.</p><p>Outside of Semeco Digital, I enjoy music production, learning new technology, community involvement, fitness, and creative projects. Curiosity is a big part of how I work, but clarity and usefulness always come first.</p></div></div></section>
  <section className="values"><div className="shell"><p className="eyebrow light"><span/> What guides my work</p><div className="value-grid"><article><span>01</span><h3>Make it useful</h3><p>Every website, campaign, and automation should solve a real business or customer problem.</p></article><article><span>02</span><h3>Keep it human</h3><p>AI can improve speed and consistency, but empathy, judgment, and relationships still matter most.</p></article><article><span>03</span><h3>Be transparent</h3><p>Clear scope, realistic expectations, and honest starting prices create stronger partnerships.</p></article></div></div></section>
  <section className="human-ai shell"><div className="ai-core"><span>SD</span><small>HUMAN + AI</small></div><div><p className="eyebrow"><span/> The Semeco approach</p><h2>Human judgment meets<br/><em>intelligent tools.</em></h2><p>I use AI to support research, copy development, content planning, automation, and business systems. I remain responsible for strategy, creative direction, quality control, and making sure the final work feels right for the business and its customers.</p><Link className="button primary" href="/contact">Let’s Talk About Your Business <span>↗</span></Link></div></section>
  <Footer/><Chatbot/>
</main>}
