import type { Metadata } from "next";
import Link from "next/link";
import { Chatbot, Footer, Header } from "../site-shell";

export const metadata: Metadata = {title:"Portfolio",description:"Explore Service Offers, a bilingual local-business website project by Semeco Digital, with space for future case studies.",alternates:{canonical:"/portfolio"},openGraph:{title:"Portfolio | Semeco Digital",description:"Selected website, copywriting, bilingual, SEO, and brand work.",url:"/portfolio"}};
const delivered=["Website strategy","Website design","Copywriting","Responsive development","Bilingual English and Spanish experience","Quote and appointment forms","Basic SEO","Brand refresh"];

export default function Portfolio(){return <main><Header/>
  <section className="page-hero shell"><p className="eyebrow"><span/> Selected work</p><h1>Thoughtful digital work.<br/><em>Built around the business.</em></h1><p>This portfolio begins with Service Offers and is designed to grow as new websites, marketing systems, and automations are launched.</p></section>
  <section className="shell featured-project"><div className="case-art large"><div className="case-wordmark"><small>FEATURED PROJECT · COMING SOON</small><strong>SERVICE<br/>OFFERS</strong><span>Pilot Point, Texas</span></div><div className="project-link-placeholder">Project image will be added at launch</div></div><div className="featured-project-copy"><p className="eyebrow"><span/> Website · Copy · Bilingual</p><h2>Service Offers</h2><p className="project-summary">A family-owned tax, insurance, immigration-document-support, and notary business serving Pilot Point, Texas.</p><div className="project-status"><b>COMING SOON</b><span>The public website is still being prepared.</span></div><h3>Services provided</h3><ul className="case-services">{delivered.map(item=><li key={item}>{item}</li>)}</ul><div className="disabled-links"><span>Live website link <b>Coming soon</b></span><span>Case study link <b>Coming soon</b></span></div></div></section>
  <section className="project-story shell"><article><span>01 · PROBLEM</span><h3>One business, many important services</h3><p>Service Offers needed a clear digital home that could explain several service categories and support both English- and Spanish-speaking customers without making the experience feel overwhelming.</p></article><article><span>02 · SOLUTION</span><h3>A clearer bilingual customer journey</h3><p>Semeco Digital organized the information, refreshed the brand presentation, and designed responsive quote and appointment paths around the questions customers are most likely to have.</p></article><article><span>03 · OUTCOME</span><h3>To be documented after launch</h3><p>No measurable results are being claimed before the website is public and has reliable analytics. The future case study will report only verified outcomes.</p></article></section>
  <section className="future shell"><span>+</span><div><h2>Future projects will live here.</h2><p>Additional project imagery, live links, case studies, problems, solutions, and verified outcomes can be added without redesigning this page.</p></div></section>
  <section className="cta-section"><div className="shell cta-inner"><h2>Need a clearer digital home<br/><em>for your business?</em></h2><Link className="button cream" href="/contact">Book a Free Consultation <span>↗</span></Link></div></section><Footer/><Chatbot/>
</main>}
